server.port=8080
spring.application.name=alpha-decode


# to import the db config
spring.config.import=classpath:db.properties

#for hibernate
#the ddl-auto=update line is just for dev, set to none/validate before prod cus data integrity issues
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

#health checks
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

#prepends /api to all controller routes
spring.mvc.servlet.path=/api