server.port=8080
spring.application.name=alpha-decode

# Database — set these in your .env file (see .env.example)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#for hibernate
#the ddl-auto=update line is just for dev, set to none/validate before prod cus data integrity issues
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

#health checks
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

# allows frontend to send lowercase instead of uppercase enums (role,difficulty,etc)
spring.jackson.mapper.accept-case-insensitive-enums=true

# allows backend to return enums as lowercase e.g. user instead of USER, requires overriding tostring
spring.jackson.serialization.write-enums-using-to-string=true

#allow db connection to close gracefully
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRY_MS:86400000}